name: Issue
description: Miscellaneous issues are closed immediately. If you have no intention of returning useful information to the community, you have no right to post an issue here. Please withdraw.
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible to convey the history of your problem. Sloppy issues will be closed immediately. If there is no response for 5 days after the last reply, the bot will automatically close the issue.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: true
      options:
        - Feature Request
        - Documentation Feature Request
        - Others
    validations:
      required: true
  - type: input
    id: onnx2tf-version
    attributes:
      label: onnx2tf version number
      description: Please list the version number of onnx2tf used.
      placeholder: x.x.x
    validations:
      required: true
  - type: textarea
    id: Download-URL-for-ONNX
    attributes:
      label: Download URL for ONNX
      description: Please include the URL where you quoted the ONNX file (.onnx).
    validations:
      required: true
  - type: textarea
    id: parameter-replacement-json
    attributes:
      label: Parameter Replacement JSON
      description: Please include the Parameter Replacement JSON.
      render: json
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Please describe the current and expected behaviour, and attach all files/info needed to reproduce the situation if applicable. If the minimum information required to reproduce the event is not provided, it will be closed immediately.
    validations:
      required: true
