name: Issue
description: Miscellaneous issues are closed immediately. If you have no intention of returning useful information to the community, you have no right to post an issue here. Please withdraw.
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible to convey the history of your problem. Sloppy issues will be closed immediately. If there is no response for 5 days after the last reply, the bot will automatically close the issue.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: true
      options:
        - Feature Request
        - Documentation Feature Request
        - Others
    validations:
      required: true
  - type: input
    id: onnx2tf-version
    attributes:
      label: onnx2tf version number
      description: Please list the version number of onnx2tf used.
      placeholder: x.x.x
    validations:
      required: true
  - type: textarea
    id: Download-URL-for-ONNX
    attributes:
      label: Download URL for ONNX
      description: Please include the URL where you quoted the ONNX file (.onnx).
      placeholder: https://abcxyz.aa.en/xxxx.onnx
    validations:
      required: true
  - type: textarea
    id: parameter-replacement-json
    attributes:
      label: Parameter Replacement JSON
      description: Please include the Parameter Replacement JSON.
      render: json
      placeholder: |
        {
          "format_version": 1,
          "operations": [
            {
              "op_name": "StatefulPartitionedCall/Cast_3",
              "param_target": "attributes",
              "param_name": "to",
              "values": 1
            },
            {
              "op_name": "Resize__697",
              "param_target": "inputs",
              "param_name": "Concat__696:0",
              "values": [26,26]
            },
            {
              "op_name": "Transpose__927",
              "param_target": "attributes",
              "param_name": "perm",
              "values": [0,1,2,3]
            },
            {
              "op_name": "StatefulPartitionedCall/functional_1/max_unpooling2d_2/Reshape_1",
              "param_target": "inputs",
              "param_name": "const_fold_opt__911",
              "values": [4,131072]
            },
            {
              "op_name": "Reshape_25",
              "param_target": "outputs",
              "param_name": "onnx::InstanceNormalization_270",
              "post_process_transpose_perm": [0,2,1]
            }
          ]
        }
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Please describe the current and expected behaviour, and attach all files/info needed to reproduce the situation if applicable. If the minimum information required to reproduce the event is not provided, it will be closed immediately.
    validations:
      required: true
