name: Issue
description: Miscellaneous issues are closed immediately. If you have no intention of returning useful information to the community, you have no right to post an issue here. Please withdraw.
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible to convey the history of your problem. Sloppy issues will be closed immediately. If there is no response for 5 days after the last reply, the bot will automatically close the issue.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: true
      options:
        - Feature Request
        - Documentation Feature Request
        - Others
    validations:
      required: true
  - type: dropdown
    id: os-type
    attributes:
      label: OS
      description: OS of your working machine.
      multiple: false
      options:
        - Linux
        - Windows
        - OSX
        - Others
    validations:
      required: true
  - type: input
    id: onnx2tf-version
    attributes:
      label: onnx2tf version number
      description: Please list the version number of onnx2tf used. `onnx2tf -V`
      placeholder: x.x.x
    validations:
      required: true
  - type: input
    id: onnx-version
    attributes:
      label: onnx version number
      description: Please list the version number of onnx used. `pip show onnx | grep Version`
      placeholder: x.x.x
    validations:
      required: true
  - type: input
    id: onnxruntime-version
    attributes:
      label: onnxruntime version number
      description: Please list the version number of onnx used. `pip show onnxruntime onnxruntime-gpu | grep Version`
      placeholder: x.x.x
    validations:
      required: true
  - type: input
    id: onnxsim-onnx-simplifier-version
    attributes:
      label: onnxsim (onnx_simplifier) version number
      description: Please list the version number of onnx used. `pip show onnxsim | grep Version`
      placeholder: x.x.x
    validations:
      required: true
  - type: input
    id: tensorflow-version
    attributes:
      label: tensorflow version number
      description: Please list the version number of tensorflow used. `pip show tensorflow | grep Version`
      placeholder: x.x.x
    validations:
      required: true
  - type: textarea
    id: Download-URL-for-ONNX
    attributes:
      label: Download URL for ONNX
      description: Please include the URL where you quoted the ONNX file (.onnx).
      placeholder: https://abcxyz.aa.en/xxxx.onnx
    validations:
      required: true
  - type: textarea
    id: parameter-replacement-json
    attributes:
      label: Parameter Replacement JSON
      description: Please include the Parameter Replacement JSON.
      render: json
      placeholder: |
        {
          "format_version": 1,
          "operations": [
            {
              "op_name": "StatefulPartitionedCall/Cast_3",
              "param_target": "attributes",
              "param_name": "to",
              "values": 1
            },
            {
              "op_name": "Resize__697",
              "param_target": "inputs",
              "param_name": "Concat__696:0",
              "values": [26,26]
            },
            {
              "op_name": "Transpose__927",
              "param_target": "attributes",
              "param_name": "perm",
              "values": [0,1,2,3]
            },
            {
              "op_name": "StatefulPartitionedCall/functional_1/max_unpooling2d_2/Reshape_1",
              "param_target": "inputs",
              "param_name": "const_fold_opt__911",
              "values": [4,131072]
            },
            {
              "op_name": "Reshape_25",
              "param_target": "outputs",
              "param_name": "onnx::InstanceNormalization_270",
              "post_process_transpose_perm": [0,2,1]
            }
          ]
        }
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: |
        Please describe the current and expected behaviour, and attach all files/info needed to reproduce the situation if applicable. If the minimum information required to reproduce the event is not provided, it will be closed immediately.
        e.g.
        1. Purpose: Personal development or Research or Product development. How much impact will solving this problem have on your efforts?
        2. What: What events are occurring? What error logs are being displayed?
        3. How: How did you attempt to solve the problem yourself?
        4. Why: Why do you need this problem solved?
        5. Resources: Material you have cited or referenced other than ONNX or JSON.
      placeholder: |
        1. Purpose
        2. What
        3. How
        4. Why
        5. Resources
    validations:
      required: true
