name: Model Convert Test

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conversion-test:
    runs-on: ubuntu-20.04
    steps:
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c
      with:
        swap-size-gb: 20
    - name: Checkout onnx2tf
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install pip -U
        pip install cmake==3.22.5
        pip install onnx==1.12.0
        pip install tensorflow==2.10.0
        pip install nvidia-pyindex
        pip install onnx-graphsurgeon
        pip install protobuf==3.20.3
        pip install onnxsim
        pip install sng4onnx
        pip install onnxruntime==1.13.1
        pip install -e .
    - name: Download models
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release download 1.1.28 -p '*.onnx' -D models
        ls -l models
    - name: Run Model Convert Tests
      run: |
        python tests/test_model_convert.py -m models -o wiki -v
    - name: Update wiki content
      uses: Andrew-Chen-Wang/github-wiki-action@7f44b142379b209235c748351558937d3e7546a7
      continue-on-error: true
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_NAME: ${{ secrets.GH_REPO_OWNER }}
        GH_MAIL: ${{ secrets.GH_EMAIL }}
        EXCLUDED_FILES: "test_model_pb/"
